services:
  statping:
    image: odesenfans/statping-ng:v0.93.0
    container_name: statping
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      # --- Core server ---
      - PORT=8080
      - TZ=${TZ}
      - LANGUAGE=en
      - NAME=${SITE_NAME}
      - DESCRIPTION=${SITE_DESCRIPTION}
      - PUBLIC=true

      # --- Auth / bootstrap admin (first-run only) ---
      - ADMIN_USER=${ADMIN_USER}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_EMAIL=${ADMIN_EMAIL}

      # --- Storage (SQLite for simplicity) ---
      - DB_CONN=sqlite
      # statping-ng stores SQLite DB under /app by default; persisted via volume below

      # --- Optional mail (uncomment & set if you want email alerts) ---
      # - SMTP_HOST=smtp.example.com
      # - SMTP_PORT=587
      # - SMTP_USER=apikey
      # - SMTP_PASSWORD=xxxxx
      # - SMTP_FROM=status@aleph.cloud
      # - SMTP_TLS=true

    volumes:
      - statping-data:/app

    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 40s

  aleph-monitor:
    image: alephim/aleph-monitor:latest
    container_name: aleph-monitor
    restart: unless-stopped
    environment:
      ALEPH_SCHEDULER_API_URL: ${ALEPH_SCHEDULER_API_URL}
      ALEPH_BATCHER_ADDRESS: ${ALEPH_BATCHER_ADDRESS}
      ETHEREUM_RPC_URL: ${ETHEREUM_RPC_URL}
      RUST_LOG: info

  prometheus:
    image: prom/prometheus:v3.6.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./config/prometheus/rules:/etc/prometheus/rules:ro
      - prometheus-data:/prometheus

  alertmanager:
    image: prom/alertmanager:v0.28.0
    depends_on:
      - prometheus
    volumes:
      - ./config/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./config/alertmanager/templates:/etc/alertmanager/templates:ro
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml

volumes:
  statping-data:
  prometheus-data:

