global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'aleph-monitor'
    static_configs:
      - targets: ['aleph-monitor:8000']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']